apiVersion: v1
data:
  api_key: c2VjcmV0VmFsdWU=
kind: Secret
metadata:
  labels:
    application_id: a8d4c529
    authorino.kuadrant.io/managed-by: authorino
    key-type: app-key
    product: l2
  name: l2-key-1
type: Opaque
