apiVersion: v1
data:
  api_key: cGFzc3dvcmQ=
kind: Secret
metadata:
  labels:
    application_id: 731b0759
    authorino.kuadrant.io/managed-by: authorino
    key-type: app-key
    product: l2
  name: l2-key-2
type: Opaque
