apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: auth-static-p1
spec:
  rules:
    authentication:
      api-key-authn-54a5ff6d:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              application_id: a8d4c529
              key-type: app-key
              product: l2
        credentials:
          customHeader:
            name: app_key
        metrics: false
        priority: 0
    authorization:
      require-app-id:
        metrics: false
        patternMatching:
          patterns:
          - operator: eq
            selector: request.headers.app_id
            value: a8d4c529
        priority: 0
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: fake-api
